### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

### ISSUE THREAD

**Issue by pdcmagno** [twilio/twilio-csharp#431] opened 2018-06-23 10:39 UTC
Hi,

Seems like most of us encountered this kind of issue. Can I know how can we fix this? I tried downgrading but still this issue persists. Thanks!

*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**

### Code Snippet
```csharp
# paste code here
```

### Exception/Log
```
<place exception/log here>
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by dprothero** [comment] 2018-07-31 22:36
Do you have a .csproj you could share with us that reproduces the issue?

**Comment by leticiatech** [comment] 2018-08-03 19:29
I had the same problem, and adding this code in the Web.config file fixed it for me.
```
<dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="9.0.0.0" />
  </dependentAssembly>
```

**Comment by dprothero** [comment] 2018-08-27 21:20
Here's a quick way to fix your existing projects that have this issue: In Visual Studio, open the Package Manager Console (Tools... NuGet Package Manager... Package Manager Console) and run the following command: `Get-Project –All | Add-BindingRedirect`

**Comment by dsghi** [comment] 2018-09-14 01:27
As this has come up a few times, I did a quick [5 minute video on letting Visual Studio help you fix your binding redirects](https://www.screencast.com/t/uwobrRabc37), hopefully it will help someone.

Basically I create a new ASP.Net 4.5 MVC project, add the Twilio package, and then break the reference to demonstrate how to let VS repair it. Unfortunately, I misspoke a couple times and said reference when I meant dependency or assembly or version, but I think it still makes sense. (I was too lazy to re-record lol). Also, I did not demonstrate @dprothero's option, because why type when you can double click? ;)

**Comment by mnoreen** [comment] 2018-09-14 13:49
I guess I'm still left with wondering WHY do we need to add the binding redirects at all.  What's at the root of the issue?  It seems like there's a dependency on an older version of DLL somewhere.  Can't *that* be fixed?  I'd like to learn about that a bit more.

We have several console apps and a .NET based website.  Adding all these binding redirects is... well... just a lot of code cruft.  We use many third party DLLs (cete, afterlogic, Telerik) and don't have any of these issues, nor quite the lengthy set of *additional* dll dependencies that the Twilio library has.  I'm just wondering if something can done to improve and pare down the C# implementation.  The developer experience hasn't been great (factoring in lack of documentation resulting in hours combing the Twilio website for "examples" and trying to morph them into something more then "hello world" code).   Please understand, the Twilio service has been great and very useful.  I just think there's a lot of stumbling blocks here as a developer...

**Comment by dsghi** [comment] 2018-09-14 20:39
[Binding redirection](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions) is a .Net thing, it's the only framework that requires it. Being able to specify to the framework which assembly to use - along with other features like strong naming - are Microsoft's answers to solving [Dependency hell](https://en.wikipedia.org/wiki/Dependency_hell) (Whether they solved it or not, is rather moot). Other frameworks like Mono, Silverlight, or Xamarin automatically use the most recent version available at runtime.

If you take a few minutes to understand redirects, it's fairly simple. If you have multiple versions of a referenced assembly available for your application, or a newer version than you had when you started, you need to use a redirect to specify which version to use. This is why it frequently becomes an issue when you're upgrading dependencies or the .net runtime version in existing applications.

Microsoft is well aware that this is a pain point in the developer experience and they're always trying to improve it. Hence [automatic binding redirection](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection) was introduced in .net 4.5.1 and they're basically removed now in .Net core 2.

There was actually a great session just presented that discussed this topic at the .Net Conference on Wednesday Sept 12th, entitled [Build Great Libraries using .NET Standard](https://channel9.msdn.com/Events/dotnetConf/2018/S107). If you have a few minutes, I suggest viewing it starting around the 22:30 minute mark.

As a member of the community I want to defend Twilio for a moment. In the spirit of full disclosure, I am not an employee but I do own stock. I disagree with you on the developer experience. I have been developing a number of years with Twilio's library, and I think they do a fantastic job keeping it updated and the documentation is very thorough. Sure the examples may not demonstrate the exact situation I need, but what they do demonstrate is clear and are easy to understand. That being said, I do have a minor beef with the differences in JSON returned by the SMS API on a send vs receive. ;)

@mnoreen I completely understand your frustration. However, if you have a console app, and you're using .net 4.5.1 or greater, you shouldn't be running into the redirect problem as long as you've enabled automatic redirects. A web application, on the other hand, with many third party libraries is exactly where you'll find trouble.

The scenario that one of your other dependent libraries may update and install a new version of a key assembly like newtonsoft.json without updating your bindings would cause this, and in my experience, updates are almost always the culprit.

In closing, this isn't just a Twilio thing, it's a ,Net thing and as a developer it's something _we_ should understand and learn how to deal with.

**Comment by mnoreen** [comment] 2018-09-17 14:27
@dsghi I wanted to thank you for taking the time to craft your reply, I do appreciate it. If you will allow one more response, hopefully to clarify my thinking/question...

First, as I mentioned, I do like the Twilio service! It has been a great, overall, experience to offer text messaging integration into the work we do here at my company. I vented some old frustrations with the trial-and-error method of putting it together, but now that we've got it running, it's really kinda neat that we can do this kind of thing these days! Fortunately, there are indeed lots of examples, and it because the service is great, it does work out in the end.

Now, back to the issue at hand. I understand the ".NET thing" of binding redirection (enough so). What I'm trying to learn more about why it happens to be cropping up when using the Twilio.DLL. I've only glanced at the code in the github repo, but really that's not my level expertise. I was just wondering if the maintainers of the Twilio DLL could do something so that doesn't occur. 

I know I can allow all the binding redirects in my app.configs and web.configs.  As I mentioned, this just adds cruft that, IMHO (which admittedly doesn't matter much), isn't needed. In my perfect world, I could add the Twilio to my console app or web site (and yes, its dependencies), and that's it.

I realize I could write my own HTTP-based code to directly interact with the REST API, but... it seems to me that that's with this "helper" library is for :)  So, I'd like to (continue to) use that.

Thanks again.

**Closed** 2018-09-28 16:09 UTC
