### ISSUE TITLE
Twilio.Mvc using outdated MVC

### ISSUE THREAD

**Issue by MSDP** [twilio/twilio-csharp#166] opened 2015-05-19 17:37 UTC
When attempting to load a MVC5 Project to Azure an error is thrown for a failure to reference System.Web.Mvc v3.

The cause is that Twilio.Mvc references an outdated System.Web.Mvc:
System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
Parent: Twilio.Mvc, Version=3.4.1.0, Culture=neutral, PublicKeyToken=null

See: Twilio.Mvc.csproj

    <Reference Include="System.Web.Mvc, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"           
        <SpecificVersion>False</SpecificVersion>
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Microsoft ASP.NET\ASP.NET MVC 3\Assemblies\System.Web.Mvc.dll</HintPath>
    </Reference>

Assembly Issue:
`System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`
`Parent: Terminus Service, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`

`System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`
`Parent: Twilio.Mvc, Version=3.4.1.0, Culture=neutral, PublicKeyToken=null`

**Comment by MSDP** [comment] 2015-05-19 18:12
Tempoary Solution:

[ServiceName].dll.config 

Web Roles now get "Full-ISS" support, and Web.Config bindingRedirects are not sufficient. A new configuration must be created containing 

      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35"/>
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0"/>
      </dependentAssembly>

And the file must be set to Copy Always and Build Action None/

**Comment by devinrader** [comment] 2015-05-28 15:52
@MSDP I'm trying to see if I can replicate the issue you're seeing.

**Comment by devinrader** [comment] 2015-05-28 19:45
Hey @MSDP, with loads of help from @mikewo I was able to reproduce your issue and also validate your suggested work around.  Because this issue seems to be confined to deploying to Azure Worker Roles which today we don't see a lot of customers doing, and there is a fairly simple work-around, I'm going to mark this as not to fix and close the issue.  I've made sure to take the work-around and [document it in the wiki](https://github.com/twilio/twilio-csharp/wiki/Twilio.Mvc).

Thanks for posting the issue and the work-around.

**Closed by devinrader** 2015-05-28 19:45 UTC
