### ISSUE TITLE
Twilio.Exceptions.ApiException: 'Identity not provided'

### ISSUE THREAD

**Issue by rezabazargan** [twilio/twilio-csharp#661] opened 2023-01-10 00:34 UTC
### Issue Summary
Adding an SMS participant does not need to provide an Identity and the CreateParticipantOptions.GetParam() method returns a dictionary that contains "MessagingBinding.Address" and "MessagingBinding.ProxyAddress". But the endpoint needs the null Identity property. and would yield a 400 error when it called without Identity: "Twilio.Exceptions.ApiException: 'Identity not provided' "

### Steps to Reproduce
Call Create Method for ParticipantResource without identity 

### Code Snippet
```csharp
           string accountSid = "";
            string authToken = "";

            TwilioClient.Init(accountSid, authToken);

            var conversation = ConversationResource.Create(
                friendlyName: "Conversation"
            );
            var conversationF = ConversationResource.Fetch(
                pathSid: conversation.Sid
            );

            CreateParticipantOptions createParticipantOptions = new CreateParticipantOptions(conversationF.Sid)
            {
                MessagingBindingAddress = "+111",
                MessagingBindingProxyAddress = "+111"
            };
            var participant = ParticipantResource.Create(createParticipantOptions);
```

### Exception/Log
```
Twilio.Exceptions.ApiException
  HResult=0x80131500
  Message=Identity not provided
  Source=Twilio
  StackTrace:
   at Twilio.Clients.TwilioRestClient.ProcessResponse(Response response)
   at Twilio.Clients.TwilioRestClient.Request(Request request)
   at Twilio.Rest.Conversations.V1.Conversation.ParticipantResource.Create(CreateParticipantOptions options, ITwilioRestClient client)

```

### Technical details:
* twilio-csharp version:  6.0.1
* csharp version: 11

**Comment by Swimburger** [comment] 2023-01-10 03:17
Hi, could this be the same bug as #656? This was fixed in 6.2.0, can you upgrade?

**Comment by isha689** [comment] 2023-01-10 08:18
Hi @rezabazargan,

I tested your code and I am not able to reproduce this issue, can you please try upgrading to latest csharp-sdk version i.e. 6.2.0

**Comment by sbansla** [comment] 2023-02-08 15:00
Closing the issue because of inactivity. Issue is not reproducible in twilio 6.2.0 as mentioned before.

**Closed by sbansla** 2023-02-08 15:00 UTC
Labels: status: waiting for feedback
