### ISSUE TITLE
Breaking change introduced on Twilio.Rest.Lookups.V1.PhoneNumberResource.Carrier property

### ISSUE THREAD

**Issue by waellus** [twilio/twilio-csharp#549] opened 2020-12-03 18:48 UTC
### Issue Summary
Even if it's indicated on https://github.com/twilio/twilio-csharp/blob/a489e3d7c0110e6c130401b1bca9bced45c739fa/CHANGES.md#2020-12-02-version-5510

> **Lookups**
> - Changed `caller_name` and `carrier` properties type to object **(breaking change)**

We don't have any description or details of the object compared to the `Dictionary<string, string>` before. The `Twilio.Rest.Lookups.V1.PhoneNumberResource.Carrier` property is unusable as of now as our test account cannot get the details.

### Steps to Reproduce
1. Use `Twilio.Rest.Lookups.V1.PhoneNumberResource.Carrier` as a `Dictionary<string, string>` as in 5.50.0 (to get the carrier name for example).
2. Update nuget to 5.51.0
3. Observe compilation fails

### Code Snippet
```csharp
var phoneNumberResource = await PhoneNumberResource.FetchAsync(lookupRequest);
var carrierName = phoneNumberResource.Carrier.TryGetValue("name", out var name) ? name : null; // working as of 5.50.0, failing as of 5.51.0
```

### Exception/Log
```
Could not compile code as `Twilio.Rest.Lookups.V1.PhoneNumberResource.Carrier` property used to be `Dictionary<string, string>` as of 5.50.0 and `object` as of 5.51.0
```

### Technical details:
* twilio-csharp version: 5.51.0
* csharp version: 8.0

**Comment by joshsacks** [comment] 2020-12-03 19:00
We're having the same issue as well. If they don't release a fix, I'm thinking we might have to do this:

```
var carrierDict= JsonConvert.DeserializeObject<Dictionary<string, string>>(phoneNumberResource.Carrier);
var carrierName = phoneNumberResource.Carrier.TryGetValue("name", out var name) ? name : null;
```

**Comment by joshsacks** [comment] 2020-12-04 18:04
@eshanholtz Any chance this will be fixed?

**Comment by waellus** [comment] 2020-12-04 21:58
> 
> 
> We're having the same issue as well. If they don't release a fix, I'm thinking we might have to do this:
> 
> ```
> var carrierDict = JsonConvert.DeserializeObject<Dictionary<string, string>>(phoneNumberResource.Carrier);
> var carrierName = carrierDict.TryGetValue("name", out var name) ? name : null;
> ```

Please let know if this ended up working.

**Comment by TylerDM** [comment] 2020-12-08 19:57
If anyone else wants to see the commit, it's here https://github.com/twilio/twilio-csharp/commit/a489e3d7c0110e6c130401b1bca9bced45c739fa .  But there's no additional information in the commit message or code.

**Comment by thinkingserious** [comment] 2021-01-19 22:28
Hello @waellus,

Thank you for reporting this issue!

In order to resolve this issue, we will need to update the documentation. The solution will likely be similar to what @joshsacks provided (thank you for posting the workaround!) since we now return a generic `object`.

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by joshsacks** [comment] 2021-01-19 22:34
@thinkingserious: The workaround is not ideal. Looking at the change in the Java library, it's clear this is an issue with the Librarian code generator (the change makes even less sense in Java than it does in C#).

Is there any change you can fix Librarian to change this back to how it was? (i.e. a string dictionary)

**Comment by srajkovic** [comment] 2021-01-19 23:10
I agree with @joshsacks, this definitely feels more like a Librarian bug/regression than a documentation update required. Returning object is strictly worse than returning a meaningful type.

**Comment by TylerDM** [comment] 2021-01-20 15:34
@thinkingserious Can we get a technical answer as to why this change was made?  You're generating a lot of the code, I understand that.  But the generator was working correctly before.  Why does it not work now?  Maybe you guys switched generators?

**Comment by MSIH** [comment] 2021-06-09 12:48
Did this get fixed?

**Comment by joshsacks** [comment] 2021-06-09 13:01
Nope 😞

On Jun 9, 2021, at 8:48 AM, Make Sure IT Happens ***@***.***> wrote:

﻿

Did this get fixed?

**Comment by thinkingserious** [comment] 2021-06-09 20:26
Thank you all for the continued conversation and context! The additional comments and reactions help with prioritization. 

Internal Reference: DI-1491

**Comment by jeffvaspen** [comment] 2021-06-28 16:00
Ran across this today as a surprise breaking change in a minor version update. What is the best course of action at this point? If I make the change to use the workaround above, will I be likely to have to revert that back again in some later minor update?

**Comment by deggen40** [comment] 2021-12-22 19:34
Still waiting @thinkingserious.

**Comment by David-S-03** [comment] 2022-02-22 17:59
Has this ever been answered/fixed to anyone's satisfaction?

**Comment by john-jay** [comment] 2022-04-07 04:51
This is still a problem in v5.73. I will try 5.50 instead.

**Comment by rakatyal** [comment] 2022-08-18 22:24
Hello folks, sorry for the delayed response. The only possible fix would be changing the Carrier field back to the original Datatype. Unfortunately this would cause additional issues for the SDKs for other programming languages as well as for clients that have already updated to the latest SDK version in the meantime.

As a result, we won't be fixing this. Please use the workaround mentioned above. Sincere apologies for the inconvenience caused.

**Closed** 2022-08-19 02:40 UTC
Labels: type: docs update, status: help wanted

**Comment by JeffCalmRay** [comment] 2023-03-16 13:20
@DavidEggen thanks for your workaround, but I have noticed that the "error_code" property is an int not a string which will throw an exception when trying to deserialize.

**Comment by envilgt** [comment] 2023-08-15 20:33
@rakatyal are there any plans on providing a fully working workaround? As @JeffCalmRay pointed above, it doesn't exactly work

**Comment by chrisrestall** [comment] 2023-08-15 21:19
The error code bit @JeffCalmRay mentioned above bit us too.  Went with a typed approach containing only what we needed.
`public class TwilioPhoneCarrier
	{
		public int? error_code { get; set; }
		public string mobile_country_code { get; set; }
		public string type { get; set; }
	}`
	
	Then called deserialized accordingly:
	`TwilioPhoneCarrier carrierObject = JsonSerializer.Deserialize<TwilioPhoneCarrier>(phoneNumber.Carrier.ToString() ?? string.Empty);`
