### ISSUE TITLE
DateTime with format RFC 2822 could not be serialized

### ISSUE THREAD

**Issue by lopenchi** [twilio/twilio-csharp#708] opened 2023-10-06 19:59 UTC
### Issue Summary
To create a call, Im sending the date as described in the [documentation](https://github.com/twilio/twilio-csharp/blob/main/src/Twilio/Rest/Api/V2010/Account/CallResource.cs), with format RFC 2822

But Im getting this error:
`Twilio.Exceptions.ApiException: Could not convert string to DateTime: Thu, 25 Jul 2025 20:12:33 +00`

I found this error on stackoverflow, it could be the problem:
https://stackoverflow.com/questions/21744067/jsonconvert-deserializeobject-could-not-convert-string-to-datetime-when-using-no

### Exception/Log
```
Twilio.Exceptions.ApiException: Could not convert string to DateTime: Thu, 25 Jul 2025 20:12:33 +0000. Path 'date_created', line 1, position 166.
 ---> Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: Thu, 25 Jul 2025 20:12:33 +0000. Path 'date_created', line 1, position 166.
   at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDateTime()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Twilio.Rest.Api.V2010.Account.CallResource.FromJson(String json)
   --- End of inner exception stack trace ---
   at Twilio.Rest.Api.V2010.Account.CallResource.FromJson(String json)
   at Twilio.Rest.Api.V2010.Account.CallResource.Create(CreateCallOptions options, ITwilioRestClient client)
   at Twilio.Rest.Api.V2010.Account.CallResource.Create(IEndpoint to, IEndpoint from, String pathAccountSid, Uri url, Twiml twiml, String applicationSid, HttpMethod method, Uri fallbackUrl, HttpMethod fallbackMethod, Uri statusCallback, List`1 statusCallbackEvent, HttpMethod statusCallbackMethod, String sendDigits, Nullable`1 timeout, Nullable`1 record, String recordingChannels, String recordingStatusCallback, HttpMethod recordingStatusCallbackMethod, String sipAuthUsername, String sipAuthPassword, String machineDetection, Nullable`1 machineDetectionTimeout, List`1 recordingStatusCallbackEvent, String trim, String callerId, Nullable`1 machineDetectionSpeechThreshold, Nullable`1 machineDetectionSpeechEndThreshold, Nullable`1 machineDetectionSilenceTimeout, String asyncAmd, Uri asyncAmdStatusCallback, HttpMethod asyncAmdStatusCallbackMethod, String byoc, String callReason, String callToken, String recordingTrack, Nullable`1 timeLimit, ITwilioRestClient client)

```

### Technical details:
* twilio-csharp version:  6.14.0 
* csharp version: net6.0 -  6.0.414

**Comment by AsabuHere** [comment] 2023-10-07 15:25
Hi @lopenchi, Please share the code snippet you used which lead to this error

Thanks,
Athira

**Comment by lopenchi** [comment] 2023-10-10 15:25
Code sample: 

```
// Install the C# / .NET helper library from twilio.com/docs/csharp/install

using System;
using Twilio;
using Twilio.Rest.Api.V2010.Account;


class Program
{
    static void Main(string[] args)
    {
        // Find your Account SID and Auth Token at twilio.com/console
        // and set the environment variables. See http://twil.io/secure
        string accountSid = Environment.GetEnvironmentVariable("TWILIO_ACCOUNT_SID");
        string authToken = Environment.GetEnvironmentVariable("TWILIO_AUTH_TOKEN");

        TwilioClient.Init(accountSid, authToken);

        var call = CallResource.Fetch(pathSid: "CAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF");

        Console.WriteLine(call.To);
    }
}
```

Im using [PRISM](https://stoplight.io/open-source/prism) to mock responses from API and response looks like this:

```
{
   "account_sid" : "ACAb4dAc0CEb7C6ed2EEa3472fa688C8c0",
   "answered_by" : null,
   "api_version" : "laborum minim",
   "caller_name" : null,
   "date_created" : "Thu, 12 Jul 2026 20:12:33 +0000",
   "date_updated" : "Thu, 29 Jul 2011 20:12:33 +0000",
   "direction" : null,
   "duration" : "Lorem dolore",
   "end_time" : "Thu, 27 Jul 2027 20:12:33 +0000",
   "forwarded_from" : null,
   "from" : null,
   "from_formatted" : null,
   "group_sid" : "GP6caD4866F40AAE6c5928aEBfef5206D0",
   "parent_call_sid" : "CAB00BBFae8E022e0FBc804DE6b1E3ddd9",
   "phone_number_sid" : "PN7f5F0a3e3Ccdd7E36248be5F3c39f6Af",
   "price" : "eiusmod nulla officia",
   "price_unit" : "XDR",
   "queue_time" : null,
   "sid" : "CACCA7e45bcbB68DAbFB6132bA7B07ECa7",
   "start_time" : "Thu, 15 Jul 2014 20:12:33 +0000",
   "status" : "ringing",
   "subresource_uris" : null,
   "to" : "irure eu elit sed aute",
   "to_formatted" : null,
   "trunk_sid" : "TK34C3DA5B3FCb3db981765b098d3e0BCB",
   "uri" : null
}

```

**Comment by lopenchi** [comment] 2023-10-18 14:29
Hey @AsabuHere any update on this?

**Comment by sbansla** [comment] 2023-10-25 05:15
Hi @lopenchi 
I performing below mentioned steps:
**1. Create a call**
var call = CallResource.Create(
            twiml: new Twilio.Types.Twiml("<Response><Say>Ahoy there!</Say></Response>"),
            to: new Twilio.Types.PhoneNumber("+XYZ"),
            from: new Twilio.Types.PhoneNumber("+ABC")
        );

**2. Fetch Call**
I will fetch above call details by passing sid in path varaibles
var call = CallResource.Fetch(pathSid: "CAXYZ")

I am not getting any error. Is this the right steps for reproducing issue ?

**Comment by AlbertMukarsel** [comment] 2023-11-06 19:46
Hey! @sbansla 
We reviewed this on our side, and we found the error to be the date value itself. for mocking purposes we just created a regex to comply with the date format, but not with a real date, which was the cause for an internal method of `JsonSerializer` to fail.
This issue can be closed.

**Comment by AsabuHere** [comment] 2023-11-07 06:01
Sure, closing this issue

**Closed by AsabuHere** 2023-11-07 06:01 UTC
Labels: type: bug, status: waiting for feedback
